# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpRecord_Time', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_ID', models.IntegerField()),
                ('Event_Description', models.CharField(max_length=500)),
                ('Event_StartTime', models.CharField(max_length=5)),
                ('Event_EndTime', models.CharField(max_length=5)),
                ('Event_StartDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Event_Requirement', models.CharField(max_length=50)),
                ('Event_Street', models.CharField(max_length=50)),
                ('Event_City', models.CharField(max_length=50)),
                ('Event_State', models.CharField(max_length=2)),
                ('Event_Postal', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_ID', models.IntegerField()),
                ('Group_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Org_ID', models.IntegerField()),
                ('Org_Name', models.CharField(max_length=50)),
                ('Org_Phone', models.CharField(max_length=9)),
                ('Org_Description', models.CharField(max_length=500)),
                ('Org_Email', models.CharField(max_length=50)),
                ('Org_Street', models.CharField(max_length=50)),
                ('Org_City', models.CharField(max_length=50)),
                ('Org_State', models.CharField(max_length=2)),
                ('Org_Postal', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='OrgContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Org_Contact_Fname', models.CharField(max_length=50)),
                ('Org_Contact_Lname', models.CharField(max_length=50)),
                ('Org_Contact_Phone', models.CharField(max_length=9)),
                ('Org_contact_Email', models.CharField(max_length=50)),
                ('Org_Contact_Position', models.CharField(max_length=50)),
                ('Org_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgContactPersons', to='event.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField()),
                ('User_Password', models.CharField(max_length=50)),
                ('User_Fname', models.CharField(max_length=50)),
                ('User_Lname', models.CharField(max_length=50)),
                ('User_Username', models.CharField(max_length=50)),
                ('User_Lastlogin', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Datejoined', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Email', models.CharField(max_length=50)),
                ('User_IsActive', models.CharField(max_length=50)),
                ('User_IsSuperuser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Permission_ID', models.IntegerField()),
                ('Auth_Permission_ID', models.IntegerField()),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='event.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='event.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='Org_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Organization'),
        ),
        migrations.AddField(
            model_name='emp_record',
            name='Event_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='emp_record',
            name='Org_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Organization'),
        ),
        migrations.AddField(
            model_name='emp_record',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.User'),
        ),
    ]
