# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_EndDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_StartDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Datejoined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
