# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180307_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_MaxPax',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
