# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_maxpax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
