# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180310_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Org_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
