# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180329_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_EndTime',
            field=models.CharField(choices=[('00:00AM', '00:00'), ('00:30AM', '00:30'), ('01:00AM', '01:00'), ('01:30AM', '01:30'), ('02:00AM', '02:00'), ('02:30AM', '02:30'), ('03:00AM', '03:00'), ('03:30AM', '03:30'), ('04:00AM', '04:00'), ('04:30AM', '04:30'), ('05:00AM', '05:00'), ('05:30AM', '05:30'), ('06:00AM', '06:00'), ('06:30AM', '06:30'), ('07:00AM', '07:00'), ('07:30AM', '07:30'), ('08:00AM', '08:00'), ('08:30AM', '08:30'), ('09:00AM', '09:00'), ('09:30AM', '09:30'), ('10:00AM', '10:00'), ('10:30AM', '10:30'), ('11:00AM', '11:00'), ('11:30AM', '11:30'), ('12:00PM', '12:00'), ('00:30PM', '12:30'), ('01:00PM', '13:00'), ('01:30PM', '13:30'), ('02:00PM', '14:00'), ('02:30PM', '14:30'), ('03:00PM', '15:00'), ('03:30PM', '15:30'), ('04:00PM', '16:00'), ('04:30PM', '16:30'), ('05:00PM', '17:00'), ('05:30PM', '17:30'), ('06:00PM', '18:00'), ('06:30PM', '18:30'), ('07:00PM', '19:00'), ('07:30PM', '19:30'), ('08:00PM', '20:00'), ('08:30PM', '20:30'), ('09:00PM', '21:00'), ('09:30PM', '21:30'), ('10:00PM', '22:00'), ('10:30PM', '22:30'), ('11:00PM', '23:00'), ('11:30PM', '23:30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_StartTime',
            field=models.CharField(choices=[('00:00AM', '00:00'), ('00:30AM', '00:30'), ('01:00AM', '01:00'), ('01:30AM', '01:30'), ('02:00AM', '02:00'), ('02:30AM', '02:30'), ('03:00AM', '03:00'), ('03:30AM', '03:30'), ('04:00AM', '04:00'), ('04:30AM', '04:30'), ('05:00AM', '05:00'), ('05:30AM', '05:30'), ('06:00AM', '06:00'), ('06:30AM', '06:30'), ('07:00AM', '07:00'), ('07:30AM', '07:30'), ('08:00AM', '08:00'), ('08:30AM', '08:30'), ('09:00AM', '09:00'), ('09:30AM', '09:30'), ('10:00AM', '10:00'), ('10:30AM', '10:30'), ('11:00AM', '11:00'), ('11:30AM', '11:30'), ('12:00PM', '12:00'), ('00:30PM', '12:30'), ('01:00PM', '13:00'), ('01:30PM', '13:30'), ('02:00PM', '14:00'), ('02:30PM', '14:30'), ('03:00PM', '15:00'), ('03:30PM', '15:30'), ('04:00PM', '16:00'), ('04:30PM', '16:30'), ('05:00PM', '17:00'), ('05:30PM', '17:30'), ('06:00PM', '18:00'), ('06:30PM', '18:30'), ('07:00PM', '19:00'), ('07:30PM', '19:30'), ('08:00PM', '20:00'), ('08:30PM', '20:30'), ('09:00PM', '21:00'), ('09:30PM', '21:30'), ('10:00PM', '22:00'), ('10:30PM', '22:30'), ('11:00PM', '23:00'), ('11:30PM', '23:30')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_State',
            field=models.CharField(choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawaii', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Louisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Michigan', 'MI'), ('Minnesota', 'MN'), ('Mississippi', 'MS'), ('Missouri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('New Hampshire', 'NH'), ('New Jersey', 'NJ'), ('New Mexico', 'NM'), ('New York', 'NY'), ('North Carolina', 'NC'), ('North Dakota', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregon', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('South Carolina', 'SC'), ('South Dakota', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('West Virginia', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Org_Phone',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Org_State',
            field=models.CharField(choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawaii', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Louisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Michigan', 'MI'), ('Minnesota', 'MN'), ('Mississippi', 'MS'), ('Missouri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('New Hampshire', 'NH'), ('New Jersey', 'NJ'), ('New Mexico', 'NM'), ('New York', 'NY'), ('North Carolina', 'NC'), ('North Dakota', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregon', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('South Carolina', 'SC'), ('South Dakota', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('West Virginia', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=20),
        ),
    ]
