# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180330_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpRecord_Time', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Event_Hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addhour',
            name='Event_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
