# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0010_auto_20180330_0611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddHour',
        ),
        migrations.RemoveField(
            model_name='group',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='user_permission',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='emp_record',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='emp_record',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp_record',
            name='EmpRecord_Time',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='emp_record',
            name='Event_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Event'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Permission',
        ),
    ]
