# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20180330_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_record',
            name='Org_ID',
        ),
        migrations.AlterField(
            model_name='emp_record',
            name='Event_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_record', to='event.Event'),
        ),
    ]
