# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180330_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_record',
            old_name='Event_ID',
            new_name='Event_Description',
        ),
        migrations.AlterField(
            model_name='emp_record',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
