# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20180331_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_Hour',
        ),
    ]
