# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_event_event_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_record',
            old_name='Event_Description',
            new_name='Event_ID',
        ),
    ]
