# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20180331_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Org_Phone',
            field=models.CharField(max_length=9),
        ),
    ]
